# Generated by Django 4.2.6 on 2023-12-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_contact_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='domaine',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='vision',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
