# Generated by Django 4.2.6 on 2023-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_produit_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='images/produit'),
        ),
    ]
