# Generated by Django 4.2.6 on 2023-12-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='mots_cles',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
